projectX/customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [
    path('index', views.index, name="index"),
    path('add/', views.add, name="add"),
    path('register/', views.register, name="register"), 
    path("loginCustomer", views.loginCustomer, name="login"),
    path("logoutCustomer", views.logoutCustomer, name="logout"),
    path('sercives', views.service, name='services'),
    path('', views.home, name='home'),
    path('form', views.form, name='form'),
    path('join', views.join, name="join"),
    path('profile/<int:id>', views.profile, name='profile'),
    path('employees', views.list, name='list'),
    path("garden", views.garden, name="garden"),
    path("house", views.house, name="house"),
    path("roof", views.roof, name="roof"), 
    path("pipe", views.pipe, name="pipe")
]

projectX/projectX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('customer/', include('django.contrib.auth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectX/customer/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    firstname = models.CharField(max_length=64)
    lastname = models.CharField(max_length=64)
    age = models.IntegerField()
    email = models.EmailField(max_length=128)
    mobile = models.IntegerField()
    nic = models.IntegerField()
    gender = models.CharField(max_length=10,)
    image = models.ImageField(upload_to='images', width_field=None, height_field=None)
    garden = models.BooleanField(default=False)
    house = models.BooleanField(default=False)
    pipe = models.BooleanField(default=False)
    roof = models.BooleanField(default=False)

projectX/customer/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models  import User
from django import forms

class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    firstname = forms.CharField(max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
    lastname = forms.CharField(max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))


    class meta:
        model = User
        fields = ('username', 'firstname', 'lastname', 'email', 'password1', 'password2')


    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

projectX/customer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterUserForm
from .models import Employee

# Create your views here.
def loginCustomer(request):
    if request.method == "POST":
        username = request.POST['Username']
        password = request.POST['password']
        user = authenticate(request, username=username, password = password)
        if user is not None:
            login(request, user)
            return redirect("customer:home")
        else:
            messages.success(request, ("there is an error. try again"))
            return redirect("customer:login")

    else:
        return render(request, "customer/login.html", {})

def logoutCustomer(request):
    logout(request)
    messages.success(request, ("You are loged out"))
    return redirect("customer:login")


def index(request):
    if request.user.is_authenticated:   
        return render(request, "customer/index.html")
    else:
        messages.success(request, ("You have to log in first."))
        return redirect("customer:login")
        

def add(request):
    return render(request, "customer/register.html")

def form(request):
    if request.user.is_authenticated:
        return render(request, 'customer/form.html')
    else:
        messages.success(request, ('You have to log in first'))
        return redirect("customer:home")
        

def service(request):
    if request.user.is_authenticated:   
        return render(request, 'customer/services.html')
    else:
        messages.success(request, ('You have to log in first'))
        return redirect("customer:login")
        

def home(request):
    return render(request, 'customer/home.html')

def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid:
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
           
            user = authenticate(username=username, password=password)
            
            login(request, user)
            messages.success(request, ("You've Signed up now!"))
            return redirect("customer:home")
    else:
        form = RegisterUserForm()

    return render(request, 'customer/register.html', {
        "form": form  
    })

def join(request):
    if request.method == "POST" and request.FILES["userimage"]:
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        age = request.POST["age"]
        email = request.POST["email"]
        gender = request.POST["gender"]
        nic = request.POST["nic"]
        mobile = request.POST["mobile"]
        userimage = request.FILES["userimage"]


        if request.POST.getlist("garden"):
            garden = True
        else:
            garden = 'False'

        if request.POST.getlist("house"):
            house = True
        else:
            house = 'False'

        if request.POST.getlist("roof"):
            roof = True
        else:
            roof = 'False'

        if request.POST.getlist("pipe"):
            pipe = True
        else:
            pipe = 'False'

        if firstname and lastname and age and email and gender and nic and mobile and userimage:
            employee = Employee(
            firstname=firstname, 
            lastname=lastname, 
            age=age, 
            email=email, 
            mobile=mobile, 
            gender=gender, 
            nic=nic,
            image=userimage, 
            garden=garden, 
            house=house, 
            roof=roof, 
            pipe=pipe,
            )

            employee.save()
            return redirect("customer:list")
        
    else:
        messages.success(request, ("Attemp to join was unsuccessful"))
        return redirect("customer:form")

def profile(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'customer/index.html', {
        "employee": employee
    })

def list(request):
    if request.user.is_authenticated:
        employees = Employee.objects.all()
        return render(request, 'customer/emplist.html', {
            'employees': employees
        })
    else:
        messages.success(request, ("You have to log in first"))
        return redirect("customer:login")
        
def garden(request):
    employees = Employee.objects.all()
    return render(request, "customer/gardenn.html", {
        "employees": employees
    })

def pipe(request):
    employees = Employee.objects.all()
    return render(request, "customer/pipe.html", {
        "employees": employees
    })

def roof(request):
    employees = Employee.objects.all()
    return render(request, "customer/roof.html", {
        "employees": employees
    })

def house(request):
    employees = Employee.objects.all()
    return render(request, "customer/house.html", {
        "employees": employees
    })    

projectX/customer/templates/customer/emplist.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<h2 style="margin-left: 20px;">The list of all our employees</h2>
    <ul style="margin-left: 50px; list-style-type: none;">
        {% for employee in employees %}
            <li><a href="{% url 'customer:profile' employee.id %}">{{ employee.firstname }} {{ employee.lastname }}</a></li>
        {% endfor %}
    </ul>
    <img src="{% static 'customer/index.jpeg' %}" style="height: 200px; width: 350px; margin-left: 400px; margin-top: -100px;">
{% endblock %}

projectX/customer/templates/customer/form.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<h2 style="margin-left: 300px; margin-top: -20px">Join Our service community</h2>
<form enctype="multipart/form-data" autocomplete="off" class="row g-3 shadow" action="{% url 'customer:join' %}" method="post" style="margin-left: 20px; margin-right: 20px; margin-top: 20px; margin-bottom: 40px;">
  {% csrf_token %}
    <div class="col-md-4">
      <label for="validationDefault01" class="form-label">First name</label>
      <input name="firstname" type="text" class="form-control" id="validationDefault01" required>
    </div>
    <div class="col-md-4">
      <label for="validationDefault02" class="form-label">Last name</label>
      <input type="text" name="lastname" class="form-control" id="validationDefault02" required>
    </div>
    <div class="col-md-4">
      <label for="validationDefaultUsername" class="form-label">E-mail</label>
      <div class="input-group">
        <input type="email" name="email" class="form-control" id="validationDefaultUsername"  aria-describedby="inputGroupPrepend2" required>
      </div>
    </div>
    <div class="col-md-6">
      <label for="validationDefault03" class="form-label">Age</label>
      <input type="number" name="age" style="width: 100px;" class="form-control" id="validationDefault03" required>
    </div>
    <div class="col-md-3" style="margin-left: -350px;">
      <label for="validationDefault04" class="form-label">Gender</label>
      <select name="gender" class="form-select" aria-label="Default select example">
        <option value="Not Selected">Select</option>
        <option value="Male">Male</option>
        <option value="Female">Female</option>
        <option value="Other">Other</option>
      </select>
    </div>
    <div class="col-md-3">
      <label for="validationDefault05" class="form-label">Mobile Number</label>
      <input type="number" name="mobile" class="form-control" id="validationDefault05" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault05" class="form-label">NIC Number</label>
        <input type="number" name="nic" class="form-control" id="validationDefault05" required>
    </div>
    <div class="col-md-3">
        <label for="validationDefault05" class="form-label">Upload an image of yourself</label>
        <input type="file" name="userimage" class="form-control">
    </div>
    <h5>You have to select at least one job</h5>
    <div class="col-md-0">
      <div class="form-check">
        <input name="garden" class="form-check-input" type="checkbox" value="True" id="garden">
        <label class="form-check-label" for="invalidCheck2">
          Gardening
        </label>
      </div>
    </div>    
    <div class="col-md-0">
      <div class="form-check">
        <input  name="roof" class="form-check-input" type="checkbox" value="True" id="roof">
        <label class="form-check-label">
          Roof work
        </label>
      </div>
    </div>
    <div class="col-md-0">
      <div class="form-check">
        <input name="house" class="form-check-input" type="checkbox" value="True" id="house">
        <label class="form-check-label">
          House work
        </label>
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-check">
        <input name="pipe" class="form-check-input" type="checkbox" value="True" id="pipe">
        <label class="form-check-label">
          Pipe work
        </label>
      </div>
    </div>
    <div class="col-12">
      <button class="btn btn-primary" type="submit">Join</button>
      <input type="reset" class="btn btn-secondary" value="Reset">
    </div>
    <img src="{% static 'customer/images1.jpeg' %}" style="margin-left: 400px; width: 300px; height: 200px; margin-top: -200px;">

  </form>
  

{% endblock %}

projectX/customer/templates/customer/gardenn.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<header class="home">
    <h1>Gardening Work</h1>
    <dev>
        <ul>
            {% for emp in employees %}
               {% if emp.garden == True %}
               <li><a href="{% url 'customer:profile' emp.id %}">{{ emp.firstname }} {{ emp.lastname }}</a></li>
               {% endif %}
            {% endfor %}
        </ul>
    </dev>
    <img src="{% static 'customer/index.jpeg' %}" style="margin-left: 500px; width: 300px; height: 250px; margin-top: 100px; ">
</header>


{% endblock %}

projectX/customer/templates/customer/home.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<header class="home" style="margin-left: 20px;">
    <h1>E-Services</h1>
    <p>Best site to hire experts for your day-to-day work...</p>
    <img src="{% static 'customer/index.jpeg' %}" style="height: 200px; width: 350px; margin-left: 40px;">
    <img src="{% static 'customer/index7.png' %}" style="height: 200px; width: 350px; margin-left: 40px;">
    <img src="{% static 'customer/images8.png' %}" style="height: 200px; width: 350px; margin-left: 40px;">
    <img src="{% static 'customer/index9.jpeg' %}" style="height: 200px; width: 200px; margin-left: 40px;">

</header>


{% endblock %}

projectX/customer/templates/customer/house.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<header class="home">
    <h1>House Works</h1>
    <dev>
        <ul>
            {% for emp in employees %}
               {% if emp.house == True %}
               <li><a href="{% url 'customer:profile' emp.id %}">{{ emp.firstname }} {{ emp.lastname }}</a></li>
               {% endif %}
            {% endfor %}
        </ul>
    </dev>
    <img src="{% static 'customer/index5.jpeg' %}" style="margin-left: 500px; width: 300px; height: 250px; margin-top: 100px; ">
</header>


{% endblock %}

projectX/customer/templates/customer/index.html
{% extends 'customer/layout.html' %}
{% load static %}
{% block body %}   
    <div>
        <img src="{{ employee.image.url }}" style="width: 300px; height: 300px; margin-left: 20px; margin-top: 50px;">
        <ul style="margin-left: 400px; font-size: 30px; margin-top: -250px;">
            <li>First Name:  {{ employee.firstname }}</li>
            <li>Last Name:  {{ employee.lastname }}</li>
            <li>E-mail:  {{ employee.email }}</li>
            <li>NIC:  {{ employee.nic }}</li>
            <li>Mobile Number:  {{ employee.mobile }}</li>
            <li>Gender:  {{ employee.gender }}</li>
        </ul>
    </div>
{% endblock %}

projectX/customer/templates/customer/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <style>
        body {
            background-image: "{% static 'customer/index.jpeg' %}";
        }
    </style>
    <link rel="stylesheet" href="{% static 'customer/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <!-- Favicon -->
</head>
<body>

{% include 'customer/navbar.html' %}
    
        <br/>
        
          
        <dev>
            <div class="alert alert-warning" role="alert">
                <br/>
                {% if messages %}
                    {% for message in messages %}
                         {{ message }}
                    {% endfor %}
                {% endif %}
            </div>
            <br/>
            {% block body %}{% endblock %}
        </dev>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

projectX/customer/templates/customer/login.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
    <h1 style="margin-left: 400px;">Log In</h1>
    <form action="" autocomplete="off" method="post" style="margin-left: 30px; margin-top: 50px;">
        {% csrf_token %}
        Username: <input type="text" name="Username">
        <br>
        Password: <input type="password" name="password" style="margin-top: 30px;">
        <br/>
        <input type="submit" value="Log In" class="btn btn-primary" style="margin-top: 30px;">
        <img src="{% static 'customer/images.jpeg' %}" style="margin-left: 400px; height: 250px; width: 350px; margin-top: -100px;">
    </form>
{% endblock %}

projectX/customer/templates/customer/navbar.html
    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'customer:home' %}">E-SERVICE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-5">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'customer:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:services' %}">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:list' %}">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:logout' %}">Log Out</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:form' %}">Join us</a>
                        </li>         
                    </ul>
                </div>
            </div>
        </nav>
    {% else %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'customer:home' %}">E-SERVICE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0 ms-5">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'customer:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:services' %}">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:list' %}">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:register' %}">Sign Up</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:login' %}">Log In</a>
                        </li>           
                    </ul>
                </div>
            </div>
        </nav>
    {% endif %}

projectX/customer/templates/customer/pipe.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<header class="home">
    <h1>Pipe Repair</h1>
    <dev>
        <ul>
            {% for emp in employees %}
               {% if emp.pipe == True %}
               <li><a href="{% url 'customer:profile' emp.id %}">{{ emp.firstname }} {{ emp.lastname }}</a></li>
               {% endif %}
            {% endfor %}
        </ul>
    </dev>
    <img src="{% static 'customer/images8.png' %}" style="margin-left: 500px; width: 300px; height: 250px; margin-top: 100px; ">
</header>


{% endblock %}

projectX/customer/templates/customer/register.html
{% extends 'customer/layout.html' %}

{% block body %}
{% if form.error %}
    <h4>There was an error.</h4>
{% endif %}

<dev>
        <h2 style="margin-left: 400px;">Sign Up Now!</h2>
    <form autocomplete="off" action="{% url 'customer:register' %}" method="post" style="margin-left: 30px;">
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <input type="submit" value="Sign Up" class="btn btn-primary" id="sign">
    </form>
</dev>
{% endblock %}

projectX/customer/templates/customer/roof.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}
<header class="home">
    <h1>Roof Repair</h1>
    <dev>
        <ul>
            {% for emp in employees %}
               {% if emp.roof == True %}
               <li><a href="{% url 'customer:profile' emp.id %}">{{ emp.firstname }} {{ emp.lastname }}</a></li>
               {% endif %}
            {% endfor %}
        </ul>
    </dev>
    <img src="{% static 'customer/index7.png' %}" style="margin-left: 500px; width: 300px; height: 250px; margin-top: 100px; ">
</header>


{% endblock %}

projectX/customer/templates/customer/services.html
{% extends 'customer/layout.html' %}
{% load static %}

{% block body %}

<div class="container pt-5 pb-3">
    <h1 class="display-4 text-uppercase text-center mb-5">Our Services</h1>
    <div class="row">       
        <div class="col-lg-3 mb-2">
            <a href="{% url 'customer:house' %}">
                <div class="p-3 mb-4 btn btn-outline-primary">               
                    <h4 class="text-uppercase mb-4">House Cleaning</h4>
                    <p class="m-0">We clean you house for you for your satisfactory...</p>
                </div>
            </a>
            <img src="{% static 'customer/index9.jpeg' %}" style="height: 200px; width: 200px;">        
        </div>
        <div class="col-lg-3 mb-2">
            <a href="{% url 'customer:pipe' %}">
                <div class=" p-3 mb-4 btn btn-outline-primary">
                    <h4 class="text-uppercase mb-4">Plumber Works</h4>
                    <p class="m-0">We do your day-to-day pipe-line work... </p>
                </div>
            </a>    
            <img src="{% static 'customer/images8.png' %}" style="height: 180px; width: 280px; margin-left: -40px;">    
        </div>
        <div class="col-lg-3 mb-2">
            <a href="{% url 'customer:roof' %}">
                <div class=" p-3 mb-4 btn btn-outline-primary">               
                    <h4 class="text-uppercase mb-4">Roof Repiar</h4>
                    <p class="m-0">We do your daily constructions...</p>
                </div>
            </a>   
            <img src="{% static 'customer/index7.png' %}" style="height: 150px; width: 280px; margin-left: -40px;margin-top: 20px;">     
        </div>
        <div class="col-lg-3 mb-2">
            <a href="{% url 'customer:garden' %}">
                <div class="p-3 mb-4 btn btn-outline-primary">               
                    <h4 class="text-uppercase mb-4">Garden / Yard work</h4>
                    <p class="m-0">We clean you garden or yard for you for your satisfactory...</p>
                </div>
            </a> 
            <img src="{% static 'customer/index.jpeg' %}" style="height: 180px; width: 280px; margin-left: -20px;">       
        </div>
    </div>
</div>

{% endblock %}